README.md
oidc-js/src/client.ts
oidc-js/src/constants/messages.ts
oidc-js/src/models/client.ts
oidc-js/src/models/index.ts
oidc-js/src/models/message.ts
oidc-js/src/models/token-response.ts
oidc-js/src/models/web-worker-client.ts
oidc-js/src/models/web-worker.ts
oidc-js/src/utils/crypto.ts
oidc-js/src/utils/sign-in.ts
oidc-js/src/worker/oidc.worker.ts
oidc-js/src/worker/web-worker-client.ts
oidc-js/src/worker/web-worker.ts

>  The decoded ID token can now be obtained by using the following method.
```javascript
auth.getDecodedIDToken().then((response)=>{
// console.log(response);
}).catch((error)=>{
// console.error(error);
});
```
> ID Token validation can be disabled by setting `validateIDToken` attribute of the `config` object passed as the argument into the `initialize` method to `false`.

Implement getDecodedIDToken method and allow id token validation to be disabled

---

README.md
oidc-js/.eslintrc.js
oidc-js/src/client.ts
oidc-js/src/constants/messages.ts
oidc-js/src/utils/sign-out.ts
oidc-js/src/worker/web-worker-client.ts
samples/react-js-app/src/components/dashboard.tsx
samples/react-js-app/src/components/sign-out.tsx

> When the `signOut` method is called, the user is redirected to the identity server's page and redirected back to the SPA after successfully logging out. Since on redirection, the SPA is reloaded fresh, the `sign-out` hook wasn't calling the callback function.
> The `state` param of the logout URL is used to know if the SPA is being loaded after a logout. If it is so, then the `sign-out` hook's callback gets called.

Fix on sign-out hook not firing issue

---

oidc-js/src/constants/token.ts
oidc-js/src/models/authenticated-user.ts
oidc-js/src/models/message.ts
oidc-js/src/models/session.ts
oidc-js/src/models/token-response.ts
oidc-js/src/public-api.ts
oidc-js/src/utils/index.ts
oidc-js/src/utils/op-config.ts
oidc-js/src/utils/session-storage.ts
oidc-js/src/utils/sign-in.ts
oidc-js/src/utils/token.ts
oidc-js/src/worker/web-worker-client.ts
oidc-js/src/worker/web-worker.ts

If the tenant domain is available in the `sub`(uid) claim of the ID token, it can decoded and added to the authenticated user's detail response.
This PR adds changes to decode the tenant domain from the ID token.
Split the `sub` and extract the tenant domain.
**Regular usernames**
```
brion@wso2.com -> wso2.com
``` 
**Email usernames**
```
brion@gmail.com@wso2.com -> wso2.com
```

Implement capability to decode tenant domain from id token

---

oidc-js/src/client.ts

Prevent on sign in hook getting called when auth code request is obtained

Prevent on sign in hook getting called when auth code request is obtained

---

packages/oidc-js/README.md
packages/oidc-js/src/client.ts
packages/oidc-js/src/models/web-worker-client.ts
packages/oidc-js/src/models/web-worker.ts
packages/oidc-js/src/utils/sign-in.ts
packages/oidc-js/src/worker/oidc.worker.ts
packages/oidc-js/src/worker/web-worker-client.ts
packages/oidc-js/src/worker/web-worker.ts

> The `signIn()` method has been modified to accept an `fidp` argument that would set the `fidp` parameter in the authorization request URL. 
Sample:
```javascript
auth.signIn("fb");
```

Allow developers to specify an FIDP during sign in

---

packages/oidc-js/README.md
packages/oidc-js/src/client.ts
packages/oidc-js/src/models/client.ts
samples/using-oidc-js-sdk/react-js-app/src/index.tsx

> Resolves #61 
- `clientHost` is made optional and the default value is set to `origin`.
- `signOutRedircetURL` is made optional and the `signInRedirectURL` is set as the default value.

Set origin as the default value of clientHost 

---

packages/oidc-js/src/models/client.ts
packages/oidc-js/src/utils/sign-in.ts

> The application has to pass some custom parameters to the authorization request. This is to pass any extra non-specification parameters expected by the IDP

Add capability to pass custom params in authorize request

---

packages/oidc-js/README.md
packages/oidc-js/src/client.ts
packages/oidc-js/src/models/client.ts
packages/oidc-js/src/utils/crypto.ts
packages/oidc-js/src/utils/sign-in.ts

When validating the token, it checks the [nbf claim](https://tools.ietf.org/html/rfc7519#section-4.1.5) value to the second, hence if there is a discrepancy between the client's system time and the server time, the validation will fail resulting in the app being unresponsive (white screen).
This PR adds an option to config the leeway in seconds (default 60s).
Used the [`clockTolerance`](https://github.com/panva/jose/blob/ee6d7251036c4e778887cde61ba7db1e60cb5b8c/docs/interfaces/_types_d_.jwtclaimverificationoptions.md#clocktolerance) option in Jose to add the leeway.

Add leeway for id_tokens

---

packages/oidc-js/README.md
packages/oidc-js/src/client.ts

> Resolves #73 
The `getInstance()` method now accepts an id against which an instance of the `IdentityClient` class is stored. If no id is provided, an instance is stored against the default id. So, whenever the `getInstance()` method is called with a certain id, the relevant instance is returned. 
Example 
```javascript
const auth = IdentityClient.getInstance();
const auth2 = IdentityClient.getInstance("secondary");
```

Allow developers to create multiple instances of `IdentityClient`

---

packages/oidc-js/src/utils/op-config.ts
packages/oidc-js/src/utils/sign-in.ts

> This change will consider the endpoints sent from the application level and use them instead of the endpoints that come in the well-known call.
Part of the fix for https://github.com/wso2-enterprise/asgardio-product/issues/632

Allow to pass endpoints from app level

---

packages/oidc-js/src/worker/web-worker-client.ts

> Always get the logout url from session storage in web worker sign-out flow. This fix having two different logic for constructing sign out url.

Always get the logout url from session storage in web worker sign-out flow

---

samples/using-oidc-js-sdk/react-typescript-app/src/App.tsx

In the sample, email is displayed as `null` when the claim is not requested.
With this PR, email will be shown only if the value is defined.

Fix null issue in react sample

---

lib/rollup.config.js

>  This makes sure `buffer` and `process` are bundled with the bundle files.

Fix builtins not being bundled issue

---

packages/oidc-js/package-lock.json
packages/oidc-js/package.json
packages/oidc-js/src/utils/sign-in.ts

Update the `idtoken` decoding technique from atob(ASCII to binary) to base64url.
Fixes https://github.com/wso2-enterprise/asgardeo-product/issues/4536
Avoid the occurance of ID token validation/decoding issues in the sign-in pages of console and myaccount apps. 
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> Provide high-level details about the samples related to this feature
> None

Update the idtoken decoding technique with base64url library

---

packages/oidc-js/src/utils/op-config.ts

When the OP config request fails, SDK should fallback to URLs provided in the SDK init object (`requestParams.endpoints`). But there is a bug in the URL resolution logic where `requestParams.endpoints` are treated as relative paths.
This PR fixes the URL resolution logic.
Treat all the `requestParams.endpoints` as absolute paths.

Fix OP config request fallback URLs

---

README.md
lib/src/core/authentication-core.ts
lib/src/models/custom-grant.ts

This PR:
-  resolves: #145 
-  updates README
Above mentioned issue id fixed by adding an optional token endpoint to the custom grant configuration and if that endpoint is provided, that is set as the token endpoint of `requestCustomGrant` method.
wso2-enterprise/choreo#6561

Optional token endpoint for custom grant configuration

---

README.md
lib/src/authentication-client.ts
lib/src/core/authentication-core.ts
lib/src/helpers/authentication-helper.ts
lib/src/models/client-config.ts
lib/src/models/user.ts

>This PR introduces an attribute called `sendCookiesInRequests` to toggle sending cookies with requests.
> This PR also improves the `BasicUserInfo` and `AuthenticatedUserInfo` interfaces.

Introduce a config attribute to send cookies and improve models 

---

lib/src/core/authentication-core.ts
lib/src/helpers/authentication-helper.ts

> At present, the username extracted from the `sub` attribute of the ID token payload is passed as the `sub` argument into the ID token validation function. This results in the DI token being invalidated when used with a SaaS app. This happens because the SaaS apps append the tenant domain to the `sub` attribute. When the username is extracted from the `sub` attribute, the tenant name is removed. 
This PR passes the `sub` attribute to the ID token validation function to fix this issue.

Fix ID token validation bug

---

README.md
lib/src/core/authentication-core.ts
lib/src/models/user.ts
lib/src/utils/authentication-utils.ts

The `sub` which contains the unique user id of the user in Identity Server is an important attribute that is needed in the application side to persist any stateful information against the user.
Return `sub` as a high level attrib when authenticated users details are requested.
Address https://github.com/asgardeo/asgardeo-auth-react-sdk/issues/64
Stop dropping `sub` in `filterClaimsFromIDTokenPayload()` function.
None
None
None
None
None
None
None
None
None
None
None
None
None

Add `sub` attribute to Authenticated state

---

lib/src/models/custom-grant.ts

Adding a new config parameter to custom grant interface to skip re calling exchange grant after refresh
Related to: https://github.com/asgardeo/asgardeo-auth-react-sdk/issues/70 
- Dependency of https://github.com/asgardeo/asgardeo-auth-spa-sdk/pull/66

extends CustomGrantConfig

---

lib/src/utils/authentication-utils.ts

This method was used to extract the tenant domain for my account and console using the subject claim of the ID token and this logic worked only when the email is used as the username. 
But ideally this functionality should be located in identity-apps. So transferred the functionality to identity-apps via [1] and deprecate this.
[1] [wso2/identity-apps#2863](https://github.com/wso2/identity-apps/pull/2863)

Deprecate getTenantDomainFromIdTokenPayload method

---

lib/src/client.ts

This will append client ID of the application to the key of the objects in the session storage. This will prevent token overriding when 2 different applications are hosted on the same subdomain (Ex: `example.com/app1` and `example.com/app2`)
Under this, the session storage will look like this.
- https://github.com/asgardeo/asgardeo-auth-react-sdk/issues/163

Append client ID to session storage artifacts

---

lib/src/client.ts

This will allow to sync the instance ID between SPA SDK and JS Core and will facilitate maintaining instance-wise entries in the session storage for all artifacts.
- https://github.com/asgardeo/asgardeo-auth-react-sdk/issues/163

Allow instance ID to be passed in the initialize() function

---

README.md
lib/src/core/authentication-core.ts
lib/src/models/client-config.ts

This PR updates the `getSignOutURL` method to send `client_id` query parameter instead of `id_token_hint` by default. This PR also introduces a new optional config `sendIdTokenInLogoutRequest`. If this is set to true, logout request will contain `id_token_hint` parameter instead of `client_id`
- https://github.com/wso2-enterprise/asgardeo-product/issues/19594

Send client_id in logout request

---

packages/oidc-js/README.md
packages/oidc-js/src/client.ts
packages/oidc-js/src/models/client.ts
packages/oidc-js/src/utils/op-config.ts
packages/oidc-js/src/utils/sign-in.ts

- This PR adds a new config, `validateIDTokenIssuer`, in order to enable/ disable ID token issuer validation.
- When the `Identity Provider Entity ID` is changed, the ID token issuer validation can be disabled if the new well-known endpoint is not configured in initialization of  `IdentityClient`.
- A new config, `validateIDTokenIssuer`, is introduced to enable/ disable ID token issuer validation.
- The default value for `validateIDTokenIssuer` would be `true` and when initializing `IdentityClient`, the required value for `validateIDTokenIssuer` can be configured.
- A new config, `validateIDTokenIssuer`, is introduced to enable/ disable ID token issuer validation.
- The default value for `validateIDTokenIssuer` would be `true` and when initializing `IdentityClient`, the required value for …

[IS 5.11.0] Add Functionality to Enable or Disable ID Token Issuer Validation

---

lib/src/core/authentication-core.ts

Improve the `isAuthenticated()` by incorporating checks for the `expires_in` attribute in the token response, aiming to improve access token validity verification.

(improvement) Improve the `isAuthenticated()` check `expires_in` validation

---

lib/src/core/authentication-core.ts

Fix `undefined` issue when `expiresIn` string is not available.
- https://github.com/asgardeo/asgardeo-auth-js-core/pull/242

(fix) Fix `undefined` issue when `expiresIn` string is not available.

---

README.md
lib/src/client.ts
lib/src/helpers/authentication-helper.ts
lib/src/helpers/crypto-helper.ts
lib/src/models/client-config.ts
lib/src/models/crypto.ts

- This PR adds a new config, `validateIDTokenIssuer`, in order to enable/ disable ID token issuer validation.
- When the `Identity Provider Entity ID` is changed, the ID token issuer validation can be disabled if the new issuer is not configured in initialization of  `AsgardeoAuthClient`.
- A new config, `validateIDTokenIssuer`, is introduced to enable/ disable ID token issuer validation.
- The default value for `validateIDTokenIssuer` would be `true` and when initializing `AsgardeoAuthClient`, the required value for `validateIDTokenIssuer` can be configured.
- A new config, `validateIDTokenIssuer`, is introduced to enable/ disable ID token issuer validation.
- The default value for `validateIDTokenIssuer` would be `true` and when initializing `AsgardeoAuthClient`, the required value for …

Add Functionality Enable or Disable ID Token Issuer Validation

---

lib/src/core/authentication-core.ts

This PR addresses the issue reported in [asgardeo/asgardeo-auth-react-sdk#208](https://github.com/asgardeo/asgardeo-auth-react-sdk/issues/208), where the keys passed into the `signIn` hook are transformed into *Snake Case*, causing compatibility issues.
- Resolve [asgardeo/asgardeo-auth-react-sdk#208](https://github.com/asgardeo/asgardeo-auth-react-sdk/issues/208)
The issue was introduced with the changes in [asgardeo/asgardeo-auth-js-core#203](https://github.com/asgardeo/asgardeo-auth-js-core/pull/203/files#diff-f34c1fc70c8dfe6982556af3ab69b70a42b7a68c9119cfa0bfa4716acd929750R120). The approach involves reverting the specific change that introduced the undesired key transformation.
*Before*
*After*
- Users should be able to pass custom parameters to the `signIn` hook without having the …

BREAKING CHANGE: Stop transforming custom auth params

---

README.md
lib/src/client.ts
lib/src/constants/client-config.ts
lib/src/core/authentication-core.ts

- The purpose of this PR is to enhance the getAuthorizationURL function by introducing support to build authorization post functions.
- The logic for building parameters of the getAuthorizationURL function is abstracted out and exposed as a new function called **getAuthorizationURLParams**.
- [Enhance getAuthorizationURL Function to Support POST Requests](https://github.com/asgardeo/asgardeo-auth-js-core/issues/250)

Enhance getAuthorizationURL function 

---

lib/src/core/authentication-core.ts

Currently, even if we pass the `client secret` along with the client id to the authorize API call, the client secret is dropped from the authorize API call in the auth-js-core level. This PR fixes the `client secret` dropping issue from the js-core level.
- https://github.com/asgardeo/asgardeo-auth-js-core/issues/252

Fix client secret dropping issue from the js-core level

---

pull_request_template.md

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
$subject

Replace quotes in the PR template with html comments

---

lib/src/helpers/authentication-helper.ts

$subject
This removes the `await` statement in the `if` condition as there is a possibility for the `await` statement to not work properly when it is evaluated in a conditional statement. 
- 
-

Fix possible bug in handleTokenResponse method

---

lib/src/core/authentication-core.ts

Fixes an issue where the revokeAccessToken method does not include client_secret in the revocation request body, causing token revocation to fail for confidential clients with the error invalid_client. This change ensures the SDK supports both public and confidential clients by conditionally appending client_secret from the config if available.
- fixes #262
- N/A

fix bug in revokeAccessToken method
