README.md

> Point the Git Issues link to the right page.

Modify git issues link

---

.github/workflows/builder.yml
.github/workflows/pr-builder.yml
README.md
oidc-js/.eslintrc.js
oidc-js/.npmrc
oidc-js/package.json
oidc-js/src/utils/op-config.ts
oidc-js/src/worker/oidc.worker.ts
oidc-js/src/worker/web-worker-client.ts
oidc-js/src/worker/web-worker.ts
package.json

>  Set up PR Builder and fixed lint issues.

Set up PR Builder and fix lint issues

---

.github/workflows/builder.yml
.github/workflows/pr-builder.yml
.github/workflows/release.yml
README.md
oidc-js/.npmrc
samples/react-js-app/package.json

>  Added build status badge to the read me file.
> Added env variable to release action.

Add build status badge to read me and add env variable to release action

---

.github/workflows/builder.yml
.github/workflows/release.yml
README.md

>  Modified the release action to copy the read me file at the root to the odic-js directory to make sure the NPM package page shows the read me file.
> Improved the read me file.

Fix read me file not being found in NPM and update the read me file

---

.github/workflows/builder.yml
lerna.json
package-lock.json
package.json

> Run the builder workflow in forked repos but prevent bumping version s
> Prevent builder getting triggered by version bumps.
> Remove version from `package json` at the root.

Fix errors in the CICD flow

---

README.md
oidc-js/src/client.ts
oidc-js/src/utils/op-config.ts
oidc-js/src/utils/session-storage.ts
oidc-js/src/utils/sign-in.ts

> Implemented a method to get the access token.
> Made sure the client secret is attached to the refresh token request.
Resolves #18 
Resolves #19

Introduce getAccessToken method and attach client secret while sending refresh token request 

---

oidc-js/package-lock.json
oidc-js/src/utils/sign-in.ts
oidc-js/src/worker/web-worker-client.ts
oidc-js/src/worker/web-worker.ts
package-lock.json
samples/react-js-app/package-lock.json

> The error message was caused by the worker's memory being persisted across hot reloading. The issue has been fixed by returning the "signed-in" message after checking if an active session exists in the memory.

Fix `auth-required` error message during hot reloading 

---

README.md

Update the version of the CDN link in the readme.

Update unpkg CDN version

---

samples/using-oidc-js-sdk/vanilla-js-app/package-lock.json
samples/using-oidc-js-sdk/vanilla-js-app/package.json
samples/using-oidc-js-sdk/vanilla-js-app/server.js

> $subject. To fix code scanning security issue.

Add request limiter to oidc js vanilla sample express server

---

.gitignore
packages/oidc-js/.eslintignore
packages/oidc-js/package-lock.json
packages/oidc-js/package.json
packages/oidc-js/tsconfig.json
packages/oidc-js/tsconfig.umd.json
packages/oidc-js/webpack.config.js
samples/using-oidc-js-sdk/vanilla-js-app/index.html
samples/using-oidc-js-sdk/vanilla-js-app/server.js

Change umd output file name and path

---

packages/oidc-js/package-lock.json
packages/oidc-js/src/models/client.ts
packages/oidc-js/src/worker/web-worker-client.ts

> Resolves https://github.com/wso2/product-is/issues/10307

Add a configuration to set the API request timeout

---

packages/oidc-js/src/models/authenticated-user.ts
packages/oidc-js/src/models/message.ts
packages/oidc-js/src/utils/session-storage.ts
packages/oidc-js/src/utils/sign-in.ts
packages/oidc-js/src/worker/web-worker-client.ts
packages/oidc-js/src/worker/web-worker.ts

Return session state with sign-on hook response

---

packages/oidc-js/src/models/authenticated-user.ts
packages/oidc-js/src/worker/web-worker-client.ts
packages/oidc-js/webpack.config.js

Fix IE compatibility issues

---

packages/oidc-js/src/utils/sign-in.ts

Fix form_post and session storage combination failing

---

packages/oidc-js/README.md

Add get service endpoint model and refresh token model to the doc

---

packages/oidc-js/package.json

Fix typescript compilation errors

---

packages/oidc-js/package-lock.json
packages/oidc-js/package.json
packages/oidc-js/src/client.ts
packages/oidc-js/src/http-client/clients/axios-http-client.ts
packages/oidc-js/src/http-client/models/axios-http-client.ts
packages/oidc-js/src/http-client/models/http-client.ts
packages/oidc-js/src/models/http-client.ts
packages/oidc-js/src/worker/web-worker.ts
samples/using-oidc-js-sdk/react-js-app/src/components/dashboard.tsx

>  This PR updates the axios library to version 0.21.0 and exposes the axios types through the SDK.

Update Axios and expose the Axios types through the SDK

---

.github/workflows/builder.yml
.github/workflows/bump-version.yml
package.json
packages/oidc-js/src/models/client.ts
packages/oidc-js/src/models/web-worker-client.ts
packages/oidc-js/src/models/web-worker.ts
packages/oidc-js/src/utils/crypto.ts
packages/oidc-js/src/utils/sign-in.ts
packages/oidc-js/src/worker/oidc.worker.ts
packages/oidc-js/src/worker/web-worker-client.ts

> Resolves https://github.com/asgardio/asgardio-js-oidc-sdk/issues/74
Used the Crypto JS library's `Base64URLDecode` method to decode the payload of the ID token. In order to support other languages, the decoded payload was also utf8 encoded.

Resolve issue when decoding id tokens

---

packages/oidc-js/README.md
packages/oidc-js/src/client.ts
packages/oidc-js/src/helpers/typeguards.ts
packages/oidc-js/src/models/client.ts
packages/oidc-js/src/utils/op-config.ts
packages/oidc-js/src/utils/session-storage.ts
packages/oidc-js/src/utils/sign-in.ts
packages/oidc-js/src/utils/sign-out.ts
packages/oidc-js/src/worker/web-worker.ts

> Resolves https://github.com/asgardio/asgardio-js-oidc-sdk/issues/57
> Resolves #17

Add inline doc comments to exposed methods

---

packages/oidc-js/README.md
packages/oidc-js/src/client.ts
packages/oidc-js/src/constants/messages.ts
packages/oidc-js/src/http-client/clients/axios-http-client.ts
packages/oidc-js/src/http-client/models/axios-http-client.ts
packages/oidc-js/src/http-client/models/http-client.ts
packages/oidc-js/src/models/client.ts
packages/oidc-js/src/models/message.ts
packages/oidc-js/src/models/web-worker-client.ts
packages/oidc-js/src/models/web-worker.ts
packages/oidc-js/src/worker/oidc.worker.ts
packages/oidc-js/src/worker/web-worker-client.ts
packages/oidc-js/src/worker/web-worker.ts

> Resolves #45 
To enable HTTP handler
```javascript
auth.enableHttpHandler();
```
To disable HTTP handler
```javascript
auth.disableHttpHandler();
```

Add enable/disable http handlers

---

packages/oidc-js/.eslintrc.js
packages/oidc-js/src/client.ts
packages/oidc-js/src/constants/endpoints.ts
packages/oidc-js/src/models/client.ts
packages/oidc-js/src/models/endpoints.ts
packages/oidc-js/src/models/web-worker-client.ts
packages/oidc-js/src/models/web-worker.ts
packages/oidc-js/src/utils/op-config.ts
packages/oidc-js/src/utils/sign-in.ts
packages/oidc-js/src/worker/web-worker-client.ts
packages/oidc-js/src/worker/web-worker.ts

> Resolves #80 
> Resolves #79

Allow developers to override endpoints and return all the endpoints through the `getServiceEndpoints` method

---

packages/oidc-js/src/public-api.ts

> Export token constants
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Export token constants

---

.github/workflows/builder.yml

> Update the builder workflow to accommodate the change to the organization's name.

Change organization name

---

.github/workflows/builder.yml

Fix the builder workflow failing to use to the secret token

---

samples/using-oidc-js-sdk/react-typescript-app/tsconfig.json

> Fix tsconfig of the react sample app to avoid version bump error.

Fix tsconfig issue

---

packages/oidc-js/README.md

Improve the Getting Started section of the ReadMe

---

samples/using-oidc-js-sdk/java-webapp/README.md

Improve the sample Java Webapp doc

---

samples/using-oidc-js-sdk/react-js-app/README.md
samples/using-oidc-js-sdk/react-js-app/src/app.css
samples/using-oidc-js-sdk/react-js-app/src/app.js
samples/using-oidc-js-sdk/react-typescript-app/README.md

> Added authentication response data view the react-js sample
> Improved json view

Add authentication response data display view to the react-js sample

---

samples/using-oidc-js-sdk/vanilla-js-app/index.html

Improve Sample Vanilla JS App

---

README.md
package.json

>  Add a deprecation message to the README file and update the git links in the `package.json` file to refer to the `v0.1.35` tag.

Add a deprecation message to the README file

---

.github/workflows/builder.yml

Update repo name

---

package.json
packages/oidc-js/README.md
packages/oidc-js/package.json

Add deprecation message to the package.

---

.github/workflows/bump-version.yml

Use github token to bump version

---

.github/workflows/release-deprecated.yml

> This workflow will be used to update the @asgardio/oidc-js package and deprecate it.

Add temporary workflow to update and deprecate oidc-js SDK

---

.github/workflows/release-deprecated.yml

Update the NPM Token in the deprecated release workflow

---

lib/src/core/authentication-core.ts

Use the URL API to compose the authorization URL

---

packages/oidc-js/src/utils/sign-in.ts

Use URL searchParams to generate query params for authorize URL

---

README.md
lerna.json
lib/package-lock.json
lib/package.json
lib/rollup.config.js
lib/src/authentication-client.ts
lib/src/constants/environments.ts
lib/src/core/authentication-core.ts
lib/src/models/user.ts
lib/src/utils/authentication-utils.ts
lib/src/utils/crypto-utils.ts
package-lock.json

> Replace `Cyprto JS` with `base64URL`, `fast-sha256`, and `randombytes`.
> Don't return attributes in the `BasicUserInfo` object if the attribute is null.
> Return `givenName`, and `familyName` with the `BasicUserInfo` object.

Replace Crypto JS with alternative libraries and edit attributes returned by getBasicUserInfo

---

README.md
lib/src/authentication-client.ts
lib/src/core/authentication-core.ts
lib/src/models/authorization-url.ts
lib/src/models/index.ts
lib/src/models/user.ts
lib/src/utils/authentication-utils.ts

>  All the claims in the id token are returned with basic user info.

Return all id token claims with basic user info

---

packages/oidc-js/src/utils/sign-in.ts
packages/oidc-js/src/utils/token.ts

Revert tenant domain changes

---

packages/oidc-js/README.md
packages/oidc-js/package-lock.json
packages/oidc-js/package.json
packages/oidc-js/polyfilled/esm.js
packages/oidc-js/polyfilled/umd.js
packages/oidc-js/rollup.config.js
packages/oidc-js/src/utils/sign-in.ts
packages/oidc-js/src/utils/token.ts

Replace Asgardio with Wso2

---

lib/src/helpers/authentication-helper.ts

Fix endpoints overriding bug

---

lib/src/authentication-client.ts
lib/src/core/authentication-core.ts
lib/src/exception/exception.ts
lib/src/exception/network-exception.ts
lib/src/helpers/authentication-helper.ts
lib/src/models/user.ts
lib/src/utils/authentication-utils.ts
lib/src/utils/crypto-utils.ts
lib/tsconfig.json

Fix strict TypeScript errors

---

lerna.json
package-lock.json
packages/oidc-js/package-lock.json
packages/oidc-js/package.json
samples/using-oidc-js-sdk/html-js-app/package-lock.json
samples/using-oidc-js-sdk/html-js-app/package.json
samples/using-oidc-js-sdk/java-webapp/package-lock.json
samples/using-oidc-js-sdk/java-webapp/package.json
samples/using-oidc-js-sdk/react-js-app/package-lock.json
samples/using-oidc-js-sdk/react-js-app/package.json
samples/using-oidc-js-sdk/react-typescript-app/package-lock.json
samples/using-oidc-js-sdk/react-typescript-app/package.json

Bump wso2-identity-oidc-js version for publishing

---

packages/oidc-js/package-lock.json
packages/oidc-js/package.json

> Install rollup node globals plugin to prevent the `process.buffer not resolved` error.

Add node globals

---

packages/oidc-js/rollup.config.js
packages/oidc-js/src/utils/crypto.ts

> $subject
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> https://github.com/asgardeo/asgardeo-auth-js-sdk/pull/136

Import globals to rollup.config.js file and update jwt header decoding.

---

lerna.json
packages/oidc-js/package-lock.json
packages/oidc-js/package.json
samples/using-oidc-js-sdk/html-js-app/package-lock.json
samples/using-oidc-js-sdk/html-js-app/package.json
samples/using-oidc-js-sdk/java-webapp/package-lock.json
samples/using-oidc-js-sdk/java-webapp/package.json
samples/using-oidc-js-sdk/react-js-app/package-lock.json
samples/using-oidc-js-sdk/react-js-app/package.json
samples/using-oidc-js-sdk/react-typescript-app/package-lock.json
samples/using-oidc-js-sdk/react-typescript-app/package.json

> Bump wso2-identity-oidc-js SDK version

[Asgardio Release] [GitHub Actions] [Release v0.1.5] Bump version

---

lerna.json
lib/package-lock.json
lib/package.json

>  Since there were release errors when releasing 0.2.6 and 0.2.7, this PR reverts back to 0.2.5

Revert back to 0.2.5 

---

.github/workflows/release.yml
lerna.json
lib/package-lock.json
lib/package.json

Add npmrc file to resolve the token issue when publishing

---

lib/src/core/authentication-core.ts
lib/src/models/data.ts

> - Made session state an optional 
> - Fixed a bug in the request-custom-grant-flow

Make sessionState optional during token request and fix custom grant bug

---

lib/src/models/data.ts

Add data layer to the model

---

lib/src/helpers/authentication-helper.ts
lib/src/models/client-config.ts

> Resolve issue with overriding OIDC endpoints through client config when there is an error calling the initial well-known endpoint.
Related issues
- Resolves https://github.com/asgardeo/asgardeo-auth-js-sdk/issues/149

Fix issue with overriding OIDC endpoints through client config

---

lib/src/models/client-config.ts

Make sendCookiesInRequests optional

---

lib/src/core/authentication-core.ts

> This PR implements the logic to update the OIDC provider metadata when the config is updated.

Update OIDC provider metadata when config is updated.

---

lib/src/authentication-client.ts
lib/src/core/authentication-core.ts

> Turn `updateConfig` method into an async method so that it can be awaited.

Make updateConfig method async

---

lib/package-lock.json
lib/src/utils/crypto-utils.ts

Fix Crypto Utils Issue For React Native

---

README.md
lib/package-lock.json
lib/package.json
lib/src/constants/environments.ts
lib/src/core/authentication-core.ts
lib/src/models/client-config.ts
lib/src/utils/crypto-utils.ts

> Reverted #166 ; Removed unused `WordArray` import.

Revert 166

---

lib/package.json
lib/src/authentication-client.ts
lib/src/constants/fetch.ts
lib/src/constants/index.ts
lib/src/core/authentication-core.ts
lib/src/data/data-layer.ts
lib/src/helpers/authentication-helper.ts
lib/src/models/fetch.ts
lib/src/models/index.ts
lib/src/models/token.ts
lib/src/utils/authentication-utils.ts
lib/yarn.lock

> Replaced `axios` with native `fetch` api.

Replaced axios with fetch

---

README.md
lib/src/core/authentication-core.ts
lib/src/helpers/authentication-helper.ts
lib/src/helpers/crypto-helper.ts
lib/src/helpers/index.ts
lib/src/models/crypto.ts
lib/src/utils/crypto-utils.ts

> This PR simplifies the `CryptoUtils` interface to make implementation simpler.
The simplified interface is as follows:
```TypeScript
interface CryptoUtils<T = any, R = any> {
/**
* Encode the provided data in base64url format.
*
* @param {T} value Data to be encoded.
*
* @returns {string} Encoded data.
*/
base64URLEncode(value: T): string;
/**
* Decode the provided data encoded in base64url format.
*
* @param {string} value Data to be decoded.
*
* @returns {string} Decoded data.
*/
base64URLDecode(value: string): string;
/**
* Generate random bytes.
*
* @param {number} length Length of the random bytes to be generated.
*
* @returns {T} Random bytes.
*/
generateRandomBytes(length: number): T;
/**
* Hash the provided data using SHA-256.
*
* @param {string} data  Data to be hashed.
*
* …
```

Simplify the CryptoUtils interface for easier implementation.

---

README.md
lib/src/client.ts
lib/src/core/authentication-core.ts
lib/src/data/data-layer.ts
lib/src/helpers/authentication-helper.ts
lib/src/public-api.ts

> This allows multiple user sessions to be stored by passing `userID` parameter.

Add multi-user capability to the SDK

---

.github/workflows/notification.yml

> $subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Add workflow to send notifications to a webhook on issue and PR creation

---

.github/workflows/notification.yml

Change repo name in notification

---

lib/src/client.ts
lib/src/constants/data.ts
lib/src/constants/parameters.ts
lib/src/core/authentication-core.ts
lib/src/helpers/authentication-helper.ts
lib/src/public-api.ts
lib/src/utils/authentication-utils.ts

>  This PR uses the state parameter to correlate the authorization request with the access token request. This resolves the PKCE inconsistency issue when multiple parallel requests are sent.

Correlate authorization request with access token request using the state parameter.

---

README.md
lib/src/helpers/authentication-helper.ts
lib/src/models/data.ts
lib/src/models/token.ts

Add created at attribute to session data

---

README.md

Fixes language errors in the readme file and formats the tables.

Format tables in readme

---

lib/src/core/authentication-core.ts

> Fix `requestCustomGrant` returning a promise instead of a json.

Fix custom grant request response issue

---

lib/src/client.ts
lib/src/constants/index.ts
lib/src/constants/oidc-endpoints.ts
lib/src/constants/server-environments.ts
lib/src/core/authentication-core.ts
lib/src/helpers/authentication-helper.ts
lib/src/models/client-config.ts
lib/src/models/oidc-provider-meta-data.ts

> This revamps the provess of OIDC endpoints retrieval process.
> This avoids sending out .well-known endpoint unless it is specified and it also simplifies the SDK for end user.
fixes https://github.com/wso2-enterprise/asgardeo-product/issues/9645
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in …

Revamp oidc endpoints retrieval

---

lib/src/helpers/authentication-helper.ts
lib/src/utils/authentication-utils.ts

Move constructServerEndpoint from helper to utils

---

lerna.json
lib/package.json

Revert back the version

---

lerna.json
lib/package.json
lib/src/client.ts
lib/src/constants/oidc-endpoints.ts
lib/src/core/authentication-core.ts
lib/src/helpers/authentication-helper.ts
lib/src/models/client-config.ts
lib/src/models/oidc-provider-meta-data.ts

> This removes deprecated fields in the auth config …

Remove deprecated fields in auth config

---

lib/src/models/client-config.ts

> This fixes the issues when both the base url config and well known endpoint config is passed in auth config.
> Link to the PR …

fix base url with well known config

---

lib/src/models/data.ts
lib/src/public-api.ts

Remove data layer interface and expose data layer class

---

lib/src/constants/data.ts
lib/src/helpers/crypto-helper.ts

> This handles the nbf claim rejection error and throws a custom SDK error.
> Link to the PR for changes to the training content …

Handle nbf claim rejection error

---

lib/src/core/authentication-core.ts

> This fixes duplicates in authorize search params. …

Fix duplicates in authorize search params

---

lib/src/client.ts
lib/src/core/authentication-core.ts

> Handles signout successful action and clearing out of the user session …

Handle signout successful action

---

lib/src/client.ts

> This replaces Replace handleSignOutSuccessful introduced by https://github.com/asgardeo/asgardeo-auth-js-sdk/pull/204  with clearUserSessionData
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …

Replace handleSignOutSuccessful with clearUserSessionData

---

lib/src/data/data-layer.ts

> Make the persistence layer extensible by making properties and functions in the data layer protected
> Link to the PR for …

Make persistence layer extensible

---

lib/src/data/data-layer.ts
lib/yarn.lock
yarn.lock

> manages custom data in persistence data layer. …

Manage custom data in persistence

---

README.md
lib/src/client.ts
lib/src/core/authentication-core.ts
lib/src/public-api.ts

> Expose crypto helper for the external …

Expose crypto helper utils

---

README.md
lib/src/client.ts
lib/src/core/authentication-core.ts

> Improvement as suggested in https://github.com/asgardeo/asgardeo-auth-js-sdk/issues/211
> Improve the readability and reduce the complexity of the code.
> Removed the signOut( ) methods in **authentication-core.ts** and **client.ts** and updated the documentation readme to reflect the changes.

Remove redundant signOut methods.

---

README.md

> update to `https://discord.gg/wso2`

Update customized discord link

---

README.md

> Add warning about using this SDK
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …

Add warning about using the SDK

---

.github/workflows/notification.yml

> This PR prevents redundant notification workflows from running when sending notifications and fixes an issue with notifications not being sent for PRs.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of …

Improve notification sending workflow

---

.github/workflows/notification.yml

> This PR resolves the issues with the notification workflow. …

Fix issues with the notifications workflow

---

.github/workflows/builder.yml
.github/workflows/notification.yml
.github/workflows/pr-builder.yml
.github/workflows/release-deprecated.yml
.github/workflows/release.yml

> This upgrades the node version to 18 as GitHub actions has deprecated node 12.
> Link to the PR for changes to the training …

Upgrade workflow to node 18

---

README.md

Update docs for changes in initialize() and constructor()

---

.github/workflows/release.yml

Change release.yml reference to auth-js-core

---

lib/src/core/authentication-core.ts
lib/src/data/data-layer.ts

Add function to store active sesion across tabs

---

lib/src/data/data-layer.ts

Fix bug with isStorageAvailable method

---

lib/src/data/data-layer.ts

Ssubject
This will fix an error occuring when `webWorker` is used as the storage option

Fix isLocalStorageAvailable function

---

lib/src/core/authentication-core.ts

$subject
The session status will be set in `signIn()` and `signOut()` functions

Handle session status in signIn, signout function

---

lib/src/core/authentication-core.ts
lib/src/helpers/authentication-helper.ts

>$subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Fix a bug in checking if all required endpoints are provided

---

lib/src/core/authentication-core.ts

URL encoding the access token request body in order to fix https://github.com/wso2-enterprise/asgardeo-product/issues/20092
- https://github.com/wso2-enterprise/asgardeo-product/issues/20092

Add support for multiple query parameters in the redirect URI of the access token request

---

lib/src/core/authentication-core.ts

URL encoding the sign-out URL in order to fix https://github.com/wso2-enterprise/asgardeo-product/issues/20294
- https://github.com/wso2-enterprise/asgardeo-product/issues/20294

Add support for multiple query parameters in the post logout redirect URI of the logout request

---

.github/workflows/release-deprecated.yml

Downgrade Node Version for release-deprecated.yml

---

.github/workflows/release-deprecated.yml

Rename NPM token for Deprecated oidc-js

---

README.md
lib/src/client.ts
lib/src/core/authentication-core.ts

This is to support tokenBindingId for token request to be passed via sign-in method
- Address https://github.com/asgardeo/asgardeo-auth-js-core/issues/257 …

Support custom params for token request via sign-in method
